# Generated by Django 5.1.3 on 2025-01-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_remove_user_first_name_remove_user_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="avatar/"),
        ),
    ]
