# Generated by Django 5.1.3 on 2025-01-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closuretable",
            name="ancestor_id",
        ),
        migrations.RemoveField(
            model_name="closuretable",
            name="descendant_id",
        ),
        migrations.AddField(
            model_name="closuretable",
            name="ancestor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="stories.storynode",
            ),
        ),
        migrations.AddField(
            model_name="closuretable",
            name="descendant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="stories.storynode",
            ),
        ),
    ]
