# Generated by Django 5.1.3 on 2025-01-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_alter_closuretable_descendant"),
    ]

    operations = [
        migrations.AddField(
            model_name="storynode",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StoryHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "first_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="head_info",
                        to="stories.storynode",
                    ),
                ),
            ],
        ),
    ]
