# Generated by Django 5.1.3 on 2025-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_storynode_published_storyhead"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyhead",
            name="tags",
            field=models.ManyToManyField(to="stories.tag"),
        ),
        migrations.AlterField(
            model_name="storyhead",
            name="title",
            field=models.CharField(default="No title", max_length=250),
        ),
    ]
