# Generated by Django 5.1.3 on 2025-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_squashed_0009_alter_storynode_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyhead",
            name="tags",
            field=models.ManyToManyField(blank=True, to="stories.tag"),
        ),
        migrations.AlterField(
            model_name="storynode",
            name="tags",
            field=models.ManyToManyField(blank=True, to="stories.tag"),
        ),
    ]
