name: tests

on:
  [workflow_dispatch, push]

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: story_node
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      DEBUG: False
      SECRET_KEY: test_secret_key
      LANGUAGE_CODE: ru
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: story_node
    steps:
      - name: add_checkout
        uses: actions/checkout@v4
      - name: Load fixtures
        run: |
          pip install -r requirements/dev.txt
          cd nodestory
          python3 manage.py migrate
          python3 manage.py loaddata fixtures/fixture.json
      - name: Run server
        run: |
          pip install -r requirements/dev.txt
          cd nodestory
          timeout 5s python3 manage.py runserver || true
      - name: Run tests
        run: |
          cd nodestory
          python3 manage.py test

  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: add_checkout
        uses: actions/checkout@v4

      - name: check_PEP8
        shell: bash
        run: |
         pip install flake8==7.1.1
         flake8 --exclude=.git,.github,migrations .
